import { useProjectData } from "../lib/use-project-data";

export function Preprocessing() {
  const { data, loading } = useProjectData();

  if (loading || !data) {
    return <div className="text-gray-400">Loading preprocessing outputs...</div>;
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold mb-2">Preprocessing</h1>
        <p className="text-gray-400">
          Exported examples generated by the Python pipeline from real project artifacts.
        </p>
      </div>

      <div className="bg-[#1a1d27] rounded-xl p-6 border border-gray-800">
        <h2 className="text-xl font-semibold mb-4">Applied Steps</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-300">
          <div className="rounded-lg bg-gray-900/50 p-4">RGB input resized to 224x224</div>
          <div className="rounded-lg bg-gray-900/50 p-4">Classical preprocessing with denoising and CLAHE</div>
          <div className="rounded-lg bg-gray-900/50 p-4">Advanced branch with bilateral filter and sharpening</div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {data.exampleImages.map((src, index) => (
          <div key={src} className="bg-[#1a1d27] rounded-xl p-4 border border-gray-800">
            <h3 className="text-sm font-semibold mb-3 text-gray-300">Example {index + 1}</h3>
            <img
              src={src}
              alt={`Pipeline example ${index + 1}`}
              className="w-full rounded-lg border border-gray-800 bg-gray-950"
            />
          </div>
        ))}
      </div>
    </div>
  );
}
